# Generated by Django 3.2.13 on 2022-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('UserName', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=64)),
                ('Sex', models.CharField(max_length=2)),
                ('TEL', models.CharField(max_length=16)),
                ('Identity', models.IntegerField()),
                ('Note', models.CharField(max_length=128)),
            ],
        ),
    ]
