# Generated by Django 3.2.13 on 2022-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOODSINFO',
            fields=[
                ('GoodID', models.IntegerField(primary_key=True, serialize=False)),
                ('GoodName', models.CharField(max_length=32)),
                ('Price', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('Type', models.CharField(max_length=16)),
                ('Stock', models.IntegerField()),
                ('QGPeriod', models.DateTimeField()),
                ('Note', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SALE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodID', models.IntegerField()),
                ('Time', models.DateTimeField()),
                ('Mount', models.IntegerField()),
                ('UserID', models.IntegerField()),
            ],
            options={
                'unique_together': {('GoodID', 'Time')},
            },
        ),
        migrations.CreateModel(
            name='CHANGELOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodID', models.IntegerField()),
                ('Time', models.DateTimeField()),
                ('Add', models.IntegerField()),
                ('Loss', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('Note', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('GoodID', 'Time')},
            },
        ),
    ]
