# Generated by Django 3.2.13 on 2022-11-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20221128_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='Add',
            field=models.IntegerField(verbose_name='添加数量'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='GoodID',
            field=models.IntegerField(verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Loss',
            field=models.IntegerField(verbose_name='损耗数量'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Note',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Time',
            field=models.DateTimeField(verbose_name='变更日期'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='UserID',
            field=models.IntegerField(verbose_name='变更人ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Cost',
            field=models.IntegerField(verbose_name='成本'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodName',
            field=models.CharField(max_length=32, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Note',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Price',
            field=models.IntegerField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='QGPeriod',
            field=models.DateTimeField(verbose_name='保质期'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Stock',
            field=models.IntegerField(verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Type',
            field=models.CharField(max_length=16, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='GoodID',
            field=models.IntegerField(verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Mount',
            field=models.IntegerField(verbose_name='销售数量'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Time',
            field=models.DateTimeField(verbose_name='销售日期'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='UserID',
            field=models.IntegerField(verbose_name='销售人员ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Identity',
            field=models.IntegerField(verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Note',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sex',
            field=models.CharField(max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='TEL',
            field=models.CharField(max_length=16, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=16, verbose_name='用户姓名'),
        ),
    ]
