# Generated by Django 3.2.13 on 2022-11-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20221129_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TEL',
            field=models.CharField(max_length=16, null=True, verbose_name='电话'),
        ),
    ]
