# Generated by Django 3.2.13 on 2022-11-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='UserID',
            field=models.CharField(max_length=16, verbose_name='变更人ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='UserID',
            field=models.CharField(max_length=16, verbose_name='销售人员ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
