# Generated by Django 3.2.13 on 2022-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20221129_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='GoodID',
            field=models.CharField(max_length=16, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodID',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='GoodID',
            field=models.CharField(max_length=16, verbose_name='商品编号'),
        ),
    ]
