# Generated by Django 3.2.13 on 2022-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20221129_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='QGPeriod',
            field=models.IntegerField(verbose_name='保质期'),
        ),
    ]
