# Generated by Django 3.2.13 on 2022-11-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_goodsinfo_qgperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='成本'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='单价'),
        ),
    ]
