# Generated by Django 3.2.13 on 2022-11-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20221130_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='Stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
    ]
